### ISSUE TITLE
libjson-rpc-cpp 1.3.0 OSX build error with hiredis 1.0.0

### ISSUE THREAD

**Issue by chenrui333** [cinemast/libjson-rpc-cpp#300] opened 2020-08-23 02:46 UTC
build error 
```
 [ 88%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/redisserver.cpp.o
 cd /tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/src/jsonrpccpp && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -Djsonrpcserver_EXPORTS -I/usr/local/include/jsoncpp -I/tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/gen -I/tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/gen/jsonrpccpp/common -I/tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/.. -std=c++11 -fprofile-arcs -ftest-coverage -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -o CMakeFiles/jsonrpcserver.dir/server/connectors/redisserver.cpp.o -c /tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/server/connectors/redisserver.cpp
 /tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/server/connectors/httpserver.cpp:78:22: error: no matching function for call to 'MHD_start_daemon'
       this->daemon = MHD_start_daemon(
                      ^~~~~~~~~~~~~~~~
 /usr/local/include/microhttpd.h:2425:1: note: candidate function not viable: no known conversion from 'int (void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)' (aka 'int (void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') to 'MHD_AccessHandlerCallback' (aka 'MHD_Result (*)(void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') for 5th argument
 MHD_start_daemon (unsigned int flags,
 ^
 /tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/server/connectors/httpserver.cpp:87:24: error: no matching function for call to 'MHD_start_daemon'
         this->daemon = MHD_start_daemon(
                        ^~~~~~~~~~~~~~~~
 /usr/local/include/microhttpd.h:2425:1: note: candidate function not viable: no known conversion from 'int (void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)' (aka 'int (void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') to 'MHD_AccessHandlerCallback' (aka 'MHD_Result (*)(void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') for 5th argument
 MHD_start_daemon (unsigned int flags,
 ^
 /tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/src/jsonrpccpp/server/connectors/httpserver.cpp:97:22: error: no matching function for call to 'MHD_start_daemon'
       this->daemon = MHD_start_daemon(
                      ^~~~~~~~~~~~~~~~
 /usr/local/include/microhttpd.h:2425:1: note: candidate function not viable: no known conversion from 'int (void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)' (aka 'int (void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') to 'MHD_AccessHandlerCallback' (aka 'MHD_Result (*)(void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') for 5th argument
 MHD_start_daemon (unsigned int flags,
 ^
 3 errors generated.
 make[2]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/httpserver.cpp.o] Error 1
 make[2]: *** Waiting for unfinished jobs....
 [ 91%] Linking CXX shared library ../../lib/libjsonrpccpp-stub.dylib
 cd /tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/src/stubgenerator && /usr/local/Cellar/cmake/3.18.1/bin/cmake -E cmake_link_script CMakeFiles/libjsonrpcstub.dir/link.txt --verbose=1
 /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -std=c++11 -fprofile-arcs -ftest-coverage -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_version 1.3.0 -o ../../lib/libjsonrpccpp-stub.1.3.0.dylib -install_name /tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/lib/libjsonrpccpp-stub.1.dylib CMakeFiles/libjsonrpcstub.dir/client/cppclientstubgenerator.cpp.o CMakeFiles/libjsonrpcstub.dir/client/jsclientstubgenerator.cpp.o CMakeFiles/libjsonrpcstub.dir/client/pyclientstubgenerator.cpp.o CMakeFiles/libjsonrpcstub.dir/codegenerator.cpp.o CMakeFiles/libjsonrpcstub.dir/helper/cpphelper.cpp.o CMakeFiles/libjsonrpcstub.dir/server/cppserverstubgenerator.cpp.o CMakeFiles/libjsonrpcstub.dir/stubgenerator.cpp.o CMakeFiles/libjsonrpcstub.dir/stubgeneratorfactory.cpp.o  ../../lib/libjsonrpccpp-common.1.3.0.dylib /usr/local/lib/libargtable2.dylib /usr/local/lib/libjsoncpp.dylib 
 make[1]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/all] Error 2
 make[1]: *** Waiting for unfinished jobs....
 cd /tmp/libjson-rpc-cpp-20200808-33932-13l52dm/libjson-rpc-cpp-1.3.0/src/stubgenerator && /usr/local/Cellar/cmake/3.18.1/bin/cmake -E cmake_symlink_library ../../lib/libjsonrpccpp-stub.1.3.0.dylib ../../lib/libjsonrpccpp-stub.1.dylib ../../lib/libjsonrpccpp-stub.dylib
 [ 91%] Built target libjsonrpcstub
 make: *** [all] Error 2
```

Full error log is in here, https://github.com/Homebrew/homebrew-core/runs/961558567

PR reference, https://github.com/Homebrew/homebrew-core/pull/59165

**Comment by cinemast** [comment] 2021-08-14 08:49
Hi!

This seems to be a duplicate of https://github.com/cinemast/libjson-rpc-cpp/issues/298.
Closing in favor of #298.

**Closed by cinemast** 2021-08-14 08:49 UTC
