### ISSUE TITLE
build for

### ISSUE THREAD

**Issue by flyfein** [cinemast/libjson-rpc-cpp#297] opened 2020-07-07 02:02 UTC

**Comment by flyfein** [comment] 2020-07-07 02:06
`D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.cpp: In member function 'virtual bool jsonrpc::HttpServer::StartListening()':
D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.cpp:80:138: error: invalid conversion from 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long long unsigned int*, void**)}' to 'MHD_AccessHandlerCallback {aka MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long long unsigned int*, void**)}' [-fpermissive]
             MHD_OPTION_THREAD_POOL_SIZE, this->threads, MHD_OPTION_SOCK_ADDR, (struct sockaddr *)(&(this->loopback_addr)), MHD_OPTION_END);
                                                                                                                                          ^
In file included from D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.h:33:0,
                 from D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.cpp:10:
D:/lib-mingw_x64/microhttpd/include/microhttpd.h:2425:1: note:   initializing argument 5 of 'MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)'
 MHD_start_daemon (unsigned int flags,
 ^~~~~~~~~~~~~~~~
D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.cpp:92:27: error: invalid conversion from 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long long unsigned int*, void**)}' to 'MHD_AccessHandlerCallback {aka MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long long unsigned int*, void**)}' [-fpermissive]
             MHD_OPTION_END);
                           ^
In file included from D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.h:33:0,
                 from D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.cpp:10:
D:/lib-mingw_x64/microhttpd/include/microhttpd.h:2425:1: note:   initializing argument 5 of 'MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)'
 MHD_start_daemon (unsigned int flags,
 ^~~~~~~~~~~~~~~~
D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.cpp:99:69: error: invalid conversion from 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long long unsigned int*, void**)}' to 'MHD_AccessHandlerCallback {aka MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long long unsigned int*, void**)}' [-fpermissive]
           MHD_OPTION_THREAD_POOL_SIZE, this->threads, MHD_OPTION_END);
                                                                     ^
In file included from D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.h:33:0,
                 from D:\lib-mingw_x64\json-rpc\libjson-rpc-cpp\src\jsonrpccpp\server\connectors\httpserver.cpp:10:
D:/lib-mingw_x64/microhttpd/include/microhttpd.h:2425:1: note:   initializing argument 5 of 'MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)'
 MHD_start_daemon (unsigned int flags,
 ^~~~~~~~~~~~~~~~
mingw32-make[2]: *** [src\jsonrpccpp\CMakeFiles\jsonrpcserver.dir\build.make:161: src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/httpserver.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:236: src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/all] Error 2
mingw32-make: *** [Makefile:151: all] Error 2`

Function pointer cast error, how should I do

**Comment by flyfein** [comment] 2020-07-07 02:10
Description is relatively simple, because my English is poor, sorry

**Comment by cinemast** [comment] 2021-08-14 08:50
This is a duplicate of #298

**Closed by cinemast** 2021-08-14 08:50 UTC
