### ISSUE TITLE
Project cannot be easy integrate with existing CMake projects as submodule

### ISSUE THREAD

**Issue by tymonx** [cinemast/libjson-rpc-cpp#85] opened 2015-02-05 10:26 UTC
When copy/clone libjson-rpc-cpp project as subdirectory/submodule to existing CMake project and add add_subdirectory(libjson-rpc-cpp) in CMakeLists.txt file, there many errors generate by CMake.

The reason is using too much CMAKE_SOURCE_* variables. Top CMakeLists.txt file should resolve this using CMAKE_CURRENT_* variable to set proper paths to all configuration files locate below.

Quick fix: set(CMAKE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

**Comment by cinemast** [comment] 2015-02-05 11:43
What is the existing CMake project, so I could reproduce it?

**Comment by tymonx** [comment] 2015-02-05 13:14
This is a non-open project :)

You can do simple test, create directory with simple CMakeLists.txt and put your project there. In CMakeLists.txt add add_subdirectory(libjson-rpc-cpp).

**Comment by cinemast** [comment] 2015-02-07 20:40
After some consideration, I think it is not really common to do that. What is the reason to use `add_subdirectory(libjson-rpc-cpp)`? Usually you build the project and then use a FindXXX.cmake script to find all the required components.

**Comment by tymonx** [comment] 2015-02-09 08:11
There are some cases, where FindXXX.cmake doesn't fit:
* when you do cross-compilation (other platforms than x86/x86_64)
* compilation isolation, compile main library/program with static libraries as submodules that have fixed version

Ok, I will soon push small change that will not effect on the existing build system. Thank you for response and keep going with that good stuff you create :)

**Comment by cinemast** [comment] 2015-02-13 19:41
Just a heads up. There have been huge refactorings on the build system from a contributor who added msvc support (#90). Keep that in mind to avoid merge conflicts.

**Comment by mgorny** [comment] 2015-04-14 07:08
Why not use CMake's [ExternalProject] (http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html) instead? That works without having to modify the build system.

**Comment by cinemast** [comment] 2015-04-14 14:44
Thank you for the hint. I will close this issue now, since this is a better solution.

**Closed by cinemast** 2015-04-14 14:44 UTC
Labels: enhancement, pullrequest-welcome

**Comment by tymonx** [comment] 2015-04-14 16:18
No, is not a better solution. ExternalProject is based on add_custom_target and all download, build and install commands are done only when you add dependencies to the project targets.

Example:
* Consider situation when you added download step to ExternalProject. The download step will be execute only when you add target dependency between ExternalProject and yours target. In REAL projects, you can have a lots of targets (e.g. $<TARGET_OBJECTS:>) that required headers from ExternalProject install step and when these targets use headers, you must add add_dependency. What is not comfortable because you must remember about nested include headers. For library is easy, because you have only one entry point e.g. in add_executable. One solution for that problem is using fixed SOURCE_DIR without DOWNLOAD and INSTALL step.

Remember that CMake has two step build, configuration and build. Using file command for download and install steps in CMake configuration you can avoid the problem with dependency between downloaded/installed headers and project.

ExternalProject is like a powerful toy, but it always be a toy. For my project that has a lots of targets (many source files) and use threads for building project, I have written script that have ExternalProject functionality (download/install/build) but it works in CMake configuration step to avoids issues with dependencies/headers and multi threads build.

**Comment by mgorny** [comment] 2015-04-14 19:30
You can add `IMPORTED` library using the external project.

**Comment by tymonx** [comment] 2015-04-15 10:21
As I wrote earlier, for library (*.so, *.a) is simply. Problem is with correlation between download/install steps also headers from ExternalProject and multi-thread build. It force you to add dependencies between all your targets that use external project headers and the ExternalProject target.

**Comment by mgorny** [comment] 2015-04-16 06:20
You don't have to declare all the steps. I just put libjson-rpc-cpp as a git submodule and start with configure step.

**Comment by tymonx** [comment] 2015-04-16 07:54
You don't see issue with ExternalProject. Consider project that:
* add ExternalProject, example target libjson-rpc-cpp-external
* import libraries as jsonrpccpp* targets, add_dependency between these libraries and libjson-rpc-cpp-external
* project has two OBJECTS targets (obj1, obj2) that are merged to one static library target (mylib) and used with target_link_libraries command
* target_link_libraries link jsonrpccpp libraries and mylib to one executable with add_executable comman
* obj1 and obj2 targets use jsonrpcpp headers

Now build with parallel options. Sometimes obj1 and obj2 can be built before ExternalProject function because you don't have any dependency between obj1, obj2 and libjson-rpc-cpp-external target. These object targets will not compile without missing headers, because ExternalProject didn't start clone project.

**Comment by mgorny** [comment] 2015-04-16 07:57
Then you should add proper cross-project dependencies. Simple as that.

**Comment by tymonx** [comment] 2015-04-16 08:05
And remember what targets use what kind of headers ? External project headers may be hidden by others headers (include by include). With many targets and many libraries ? This is very erroneous. For true cross-compilation you must always provide all libraries that come with you project (version, compilation options etc.).

I provided solution with custom ExternalProject that run in CMake configuration step (cmake command), to solve my problems.
